const QUERY = {
  POPULAR_BOOKS: "QUERY.POPULAR_BOOKS",
  BEST_REVIEWS: "QUERY.BEST_REVIEWS",
  MOST_CONSISTENT_AUTHOR: "QUERY.MOST_CONSISTENT_AUTHOR",
  HIGHEST_RATED_BOOKS_PER_GENRE_YEAR: "HIGHEST_RATED_BOOKS_PER_GENRE_YEAR",
  MOST_CONTROVERSIAL_BOOKS: "MOST_CONTROVERSIAL_BOOKS",
  ONE_HIT_WONDER: "ONE_HIT_WONDER",
  PROLIFIC_AUTHOR: "PROLIFIC_AUTHOR",
  CROSS_GENRE_AUTHOR: "CROSS_GENRE_AUTHOR",
  MOST_GENRE_AUTHOR: "MOST_GENRE_AUTHOR"
};

module.exports = {
  [QUERY.POPULAR_BOOKS]: `SELECT * 
    FROM
        (SELECT *
        FROM BOOK2
        WHERE BOOK2.TEXT_REVIEWS_COUNT IS NOT NULL
        ORDER BY BOOK2.TEXT_REVIEWS_COUNT DESC) result_set
    WHERE ROWNUM <= 10`,
  [QUERY.BEST_REVIEWS]: ``,
  [QUERY.MOST_CONSISTENT_AUTHOR]: ``,
  [QUERY.HIGHEST_RATED_BOOKS_PER_GENRE_YEAR]: ``,
  [QUERY.MOST_CONTROVERSIAL_BOOKS]: ``,
  [QUERY.ONE_HIT_WONDER]: ``,
  [QUERY.PROLIFIC_AUTHOR]: ``,
  [QUERY.CROSS_GENRE_AUTHOR]: ``,
  [QUERY.MOST_GENRE_AUTHOR]: ``
};
