export const SEARCH = {
  UPDATE_QUERY: "SEARCH.UPDATE_QUERY",
  UPDATE_RESULTS: "SEARCH.UPDATE_RESULTS",
  UPDATE_FILTERS: "SEARCH.UPDATE_FILTERS",
};

export const FAVORITE = {
  ADD: "FAVORITE.ADD",
  REMOVE: "FAVORITE.REMOVE",
  UPDATE: "FAVORITE.UPDATE",
};

export const BOOK = {
  UPDATE: "BOOK.UPDATE",
};
export const AUTHOR = {
  UPDATE: "AUTHOR.UPDATE",
};

export const QUERY = {
  POPULAR_BOOKS: "QUERY.POPULAR_BOOKS",
  BEST_REVIEWS: "QUERY.BEST_REVIEWS",
  MOST_CONSISTENT_AUTHOR: "QUERY.MOST_CONSISTENT_AUTHOR",
  HIGHEST_RATED_BOOKS_PER_GENRE_YEAR: "HIGHEST_RATED_BOOKS_PER_GENRE_YEAR",
  MOST_CONTROVERSIAL_BOOKS: "MOST_CONTROVERSIAL_BOOKS",
  ONE_HIT_WONDER: "ONE_HIT_WONDER",
  PROLIFIC_AUTHOR: "PROLIFIC_AUTHOR",
  CROSS_GENRE_AUTHOR: "CROSS_GENRE_AUTHOR",
  MOST_GENRE_AUTHOR: "MOST_GENRE_AUTHOR",
};
